# Generated by Django 3.0.8 on 2020-08-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200806_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.IntegerField(choices=[(0, 'Deleted'), (1, 'Active')], default=1, verbose_name='Status'),
        ),
    ]
