# Generated by Django 2.2.12 on 2020-07-16 11:14

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0002_auto_20200715_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Freeze'), (3, 'Finish')], verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(default=datetime.datetime(2020, 7, 23, 11, 14, 23, 412907))),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
