# Generated by Django 2.2.12 on 2020-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
