# Generated by Django 3.0.8 on 2020-08-13 08:01

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user_pic', models.ImageField(blank=True, default='user_pic_male.png', upload_to=account.models.user_directory_path)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('status', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active'), (2, 'Limited')], default=1)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Gender')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10, verbose_name='Role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
