# Generated by Django 3.0.8 on 2020-08-04 14:09

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Freeze'), (3, 'Finish')], verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 9, 29, 556103))),
                ('company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('files', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None)),
                ('description', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Freeze'), (3, 'Finish')], verbose_name='Status')),
                ('date_start', models.DateTimeField(auto_now=True)),
                ('date_end', models.DateTimeField(default=datetime.datetime(2020, 8, 11, 14, 9, 29, 556941))),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='task.Task', verbose_name='Task')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
