# Generated by Django 3.0.8 on 2020-08-12 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20200812_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 6, 23, 56, 809965)),
        ),
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Freeze'), (3, 'Finish')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Freeze'), (3, 'Finish')], default=1, verbose_name='Status'),
        ),
    ]
