# Generated by Django 3.0.8 on 2020-09-05 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0024_auto_20200903_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 12, 49, 27, 19654)),
        ),
    ]
